version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "5173:5173"
    
    volumes:
      - .:/app
      - /app/node_modules

    command: sh -c "npm install && npm run dev"

    environment:
      - CHOKIDAR_USEPOLLING=true

  

  
